- name: Create Pod
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        # TODO change something
        name: example
      spec:
        containers:
          - name: nginx
            image: nginx # Noncompliant

          - name: nginx
            image: nginx:latest # Noncompliant